apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-gist-app
  namespace: git-gist-ns
  labels:
    app: git-gist-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: git-gist-app
  template:
    metadata:
      labels:
        app: git-gist-app
    spec:
      containers:
      - name: git-gist
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"   # replace with your image
        ports:
        - containerPort: {{ .Values.service.port }}