name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests & Code Analysis
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      # Step 3: Cache pip dependencies for faster builds
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install required Python dependencies, testing, and security tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov bandit flake8 -r requirements.txt

      # Step 5: Run unit tests with coverage reporting
      - name: Run tests with coverage
        run: pytest --cov=app --cov-report=xml
        
      # Step 6: Run Bandit security scan for Python code vulnerabilities
      - name: Run security scan (Bandit)
        run: bandit -r .

      # Step 7: Run static code analysis with Flake8 (linting, PEP8 compliance)
      - name: Run static code analysis (Flake8)
        run: flake8 src --max-line-length=120 --statistics --ignore=E302

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test   # Run only if test job is successful

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to DockerHub using GitHub Secrets
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push Docker image to DockerHub
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/git-gist:${{ github.run_id }}
          
      # Step 4: Scan Docker image for vulnerabilities using Trivy
      - name: Security scan Docker image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/git-gist:${{github.run_id}}
          format: 'table'
          exit-code: '0'   # Continue pipeline even if vulnerabilities are found
        
  deploy-minikube:
    name: Deploy to Minikube
    runs-on: self-hosted
    needs: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Update values.yaml with dynamic Docker tag
      - name: Update image tag in values.yaml
        shell: powershell
        run: |
          $file = "helm/git-gist-app-chart/values.yaml"
          (Get-Content $file) -replace 'tag: ".*"', 'tag: "${{ github.run_id }}"' | Set-Content $file

      # Load Docker image into Minikube
      - name: Load Docker image into Minikube
        shell: powershell
        run: minikube image load ${{ secrets.DOCKERHUB_USERNAME }}/git-gist:${{ github.run_id }}

      # Deploy using Helm
      - name: Deploy with Helm
        shell: powershell
        run: |
          helm upgrade --install git-gist helm/git-gist-app-chart `
            --namespace git-gist-ns --create-namespace `
            -f helm/git-gist-app-chart/values.yaml

      # Verify rollout and automatic rollback on failure
      - name: Verify rollout and rollback if failed
        shell: powershell
        run: |
          try {
            kubectl rollout status deployment/git-gist-app -n git-gist-ns -w
          } catch {
            Write-Host "Rollout failed. Rolling back to previous Helm release..."
            # Get the latest successful revision
            $lastRevision = helm history git-gist -n git-gist-ns | Select-String -Pattern "deployed" | Select-Object -Last 1 | ForEach-Object { ($_ -split '\s+')[0] }
            helm rollback git-gist $lastRevision -n git-gist-ns
            Write-Host "Printing pod logs for debugging..."
            kubectl get pods -n git-gist-ns
            kubectl logs -n git-gist-ns -l app=git-gist
            exit 1
          }